#!/usr/bin/env node

/* eslint-disable node/shebang */

process.env.DXCLI_CREATE_DEFAULTS = '1'

const sh = require('shelljs')

sh.set('-ev')

sh.rm('-rf', 'tmp/test-base')
sh.exec('node bin/run base tmp/test-base')
sh.cd('tmp/test-base')
sh.exec('git add .')
sh.exec('git commit -nm init')
sh.exec('git checkout -B origin/master')
sh.exec('yarn test')
sh.exec('yarn run lint')
